mo6_ind6/Mo6 indi5/migrate_01/urls.py
from django.urls import path
from . import views


app_name = 'migrate_01'
urlpatterns = [
    path('asignatura/', views.asignaturax , name = 'asignatura'),
    path('profesor/', views.profesorx , name = 'profesor' ),
    path('alumno/', views.mostrar_alumnos, name = 'alumno'),
    path('mostrar_asignatura/', views.mostrar_asignatura, name = 'mostrar_asignatura'),
    path('add_transportista/', views.add_transportista, name ='add_transportista'),
    path('ver_alumnos/', views.mostrar_alumnos, name = 'ver_alumnos'),
    path('ver_transportistas/', views.mostar_transportistas, name ='ver_transportistas'),
    path('crear_asignatura', views.crear_asignatura, name ='crear_asignatura'),
    path('<id>/editar_asignatura', views.editar_asignatura, name = 'editar_asignatura'),
    path('<id>/eliminar_asignatura', views.eliminar_asignatura, name ='eliminar_asignatura')
]

mo6_ind6/Mo6 indi5/project_migrate/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('migrate_01.urls')),
]

mo6_ind6/Mo6 indi5/migrate_01/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    nombre = models.CharField(max_length=15)


class Profesor(models.Model):
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=25)
    escuela = models.CharField(max_length=30)
    fecha_de_contratacion = models.DateField()
    sueldo = models.IntegerField()


class Asignatura(models.Model):
    nombre = models.CharField(max_length=25)
    descripcion = models.CharField(max_length=250) 
    departamento_id = models.ForeignKey(Departamento,on_delete=models.CASCADE, null=True)
    profesor_id = models.ForeignKey(Profesor,on_delete=models.CASCADE, null =True)

    class Meta:
        ordering = ['id']


class Curso(models.Model):
    nombre = models.CharField(max_length=40)
    profesor_id = models.ForeignKey(Profesor,on_delete=models.CASCADE, null= True)
    asignatura_id = models.ForeignKey(Asignatura,on_delete=models.CASCADE)


class Transportista(models.Model):
    nombre = models.CharField(max_length=30)
    patente = models.CharField(max_length=6)


class Alumno(models.Model):
    nombre = models.CharField(max_length=35)
    Edad = models.IntegerField()
    run = models.CharField(max_length=10, primary_key=True)
    transportista_id = models.ForeignKey(Transportista,on_delete=models.CASCADE)
    curso_id = models.ForeignKey(Curso,on_delete=models.CASCADE)

mo6_ind6/Mo6 indi5/migrate_01/forms.py
from .models import Asignatura
from django import forms

class AsignaturaFormularioForms(forms.ModelForm):
    class Meta:
        model= Asignatura
        fields='__all__'

mo6_ind6/Mo6 indi5/migrate_01/views.py
from django.shortcuts import render, redirect
from .models import Departamento,Asignatura,Profesor,Alumno,Transportista
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import AsignaturaFormularioForms
# Create your views here.

def asignaturax(request):
    departamento = Departamento.objects.create(
        nombre='filosofia'
    )
    Departamento.objects.values()
    departamento.save()
    for i in range(0,5):
        asignatura = Asignatura(nombre= 'Walter',
        descripcion = 'walter es muy pesaito',
        )    
    asignatura.save()
    asignatura = Asignatura.objects.values()
    context = {'asig': asignatura}    
    return render(request, 'migrate_01/asignatura.html', context)

def add_transportista(request):
    for i in range(0,5):
        transportista = Transportista(nombre= 'Claudio',
        patente= 'AZDB12'
        )
    transportista.save()
    transportista = Transportista.objects.values()
    context = {'transportista': transportista}
    return render(request, 'migrate_01/transportistas.html', context)

def profesorx(request):
    for i in range(0,5):
        profe = Profesor(nombre= 'Claudio',
        apellido = 'Caniullan',
        escuela = 'Manuel de salas',
        fecha_de_contratacion = '2017-02-28',
        sueldo = 1100000
        )
    profe.save()
    profe = Profesor.objects.values()
    context = {'profe': profe}
    return render(request, 'migrate_01/profesor.html', context)

#MUESTRA ALUMNOS
def mostrar_alumnos(request):
    listar_alumnos = list(Alumno.objects.all().values())
    datos = {'alumnos': listar_alumnos}
    return render(request,'migrate_01/ver_alumnos.html', context= datos)

def mostrar_asignatura(request):
    listar_asignatura = list(Asignatura.objects.all().values())
    datos = {'asignatura': listar_asignatura}
    return render(request,'migrate_01/ver_asignatura.html', context= datos)

#MUESTRA TRANSPORTISTAS
def mostar_transportistas(request):
    lista_transportista = list(Transportista.objects.all().values())
    datos = {'transportistas': lista_transportista}
    return render(request,'migrate_01/ver_transportistas.html', context= datos)

#CREAR ASIGNATURA
def crear_asignatura(request):
    asignatura = AsignaturaFormularioForms(request.POST or None)
    context = {'asignatura': asignatura}
    if asignatura.is_valid():
        form_data = asignatura.cleaned_data
        Asignatura.objects.create(
                    nombre=form_data['nombre'], 
					descripcion=form_data['descripcion'], 
					departamento_id=form_data['departamento_id'], 
					profesor_id=form_data['profesor_id'],
                    )
        return redirect('migrate_01:mostrar_asignatura')
    return render(request, 'migrate_01/crear_asignatura.html', context)

#EDITAR ASIGNATURA
def editar_asignatura(request, id):
    asignatura = Asignatura.objects.filter(id=id).values()[0]
    formulario_asignatura = AsignaturaFormularioForms(request.POST or None, initial=asignatura)    
    if formulario_asignatura.is_valid():
        form_data = formulario_asignatura.cleaned_data
        Asignatura.objects.filter(id=id).update(
                    nombre=form_data['nombre'], 
					descripcion=form_data['descripcion'], 
					departamento_id=form_data['departamento_id'], 
					profesor_id=form_data['profesor_id'],
                    )

        return redirect('migrate_01:mostrar_asignatura')
    context = {'formulario_asignatura': formulario_asignatura, 'id' : id}
    return render(request, 'migrate_01/editar_asignatura.html', context)

#ELIMINAR ASIGNATURA

def eliminar_asignatura(request, id):
    if request.method == "POST":
        Asignatura.objects.filter(id=id).delete()
        return redirect('migrate_01:mostrar_asignatura')
    context = {'id': id} 
    return render(request, "migrate_01/confirmar_delete.html", context)

class CrearAsignatura(CreateView):
    model= AsignaturaFormularioForms 
    fields= '__all__'
    success_url = reverse_lazy('migrate_01:asignatura')

class EliminarAsignatura(DeleteView):
    model= AsignaturaFormularioForms 
    fields= '__all__'
    success_url = reverse_lazy('migrate_01:asignatura')

class EditarAsignatura(UpdateView):
    model= AsignaturaFormularioForms 
    fields= '__all__'
    success_url = reverse_lazy('migrate_01:asignatura')

class ListarAsignatura(ListView):
    model= AsignaturaFormularioForms 
    fields= '__all__'
    success_url = reverse_lazy('migrate_01:lista_asignatura')

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/asignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in asig  %}
    <p>{{i}}</p>
    {% endfor %}

</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/confirmar_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'migrate_01:eliminar_asignatura' id=id %}" method="POST"> 
        {% csrf_token %} 
        Está seguro de eliminar la asignatura con id = {{id}}? 
        <input type="submit" value="Sí" /> 
        <a href="{% url 'migrate_01:mostrar_asignatura' %}">Cancelar</a> 
    </form> 
</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/crear_asignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{asignatura.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'migrate_01:mostrar_asignatura' %}"><button type="button">Cancelar</button></a>
    </form>
</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/crearasignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST"></form>
    <table class="table">
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>departamento_id</th>
            <th>profesor_id</th>
            <th></th>
            <th></th>
        </tr>    

    {% for i in AsignaturaFormularioForms_list  %}
        <tr>
            <td>{{i.nombre}}</td>
          <td>{{i.Descripcion}}</td>
            <td>{{i.departamento_id}}</td>
            <td>{{i.profesor_id}}</td>
            <td>
                <a class="boton" href="{% url 'formularios:editar_guitarra_db' id=guitarra.id %}"> Editar</a>
            </td>
            <td>
                <a class="boton" href="{% url 'formularios:eliminar_guitarra_db' id=guitarra.id %}"> Eliminar</a>
            </td>
        </tr>
    {% endfor %}
    </table>

</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/editar_asignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editando asignatura id: {{id}}</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{formulario_asignatura.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'migrate_01:mostrar_asignatura' %}"><button type="button">Cancelar</button></a>

    </form>
</body>

</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/profesor.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    <title>Tecnomarket</title>
</head>

    {% for i in profe  %}
    <p>{{i}}</p>
    {% endfor %}



</html>
    
    

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/transportistas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in transportista  %}
    <p>{{i}}</p>
    {% endfor %} 
</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/ver_alumnos.html
<!DOCTYPE html>

    <html lang="en">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
        <title>Tecnomarket</title>
    </head>
    <body>
        <h2>Listado de Alumnos</h2>
        <table class="table">
            <tr>
                <th>Nombre</th>
                <th>Edad</th>
                <th>run</th>
                <th>transportista_id</th>
                <th>curso_id</th>
            </tr>    

        {% for alumno in alumnos %}
            <tr>
                <td>{{alumno.nombre}}</td>
                <td>{{alumno.Edad}}</td>
                <td>{{alumno.run}}</td>
                <td>{{alumno.transportista_id_id}}</td>
                <td>{{alumno.curso_id_id}}</td>
            </tr>
        {% endfor %}
        
    </body> 

</html>
    
    

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/ver_asignatura.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'migrate_01/css/style.css' %}">
  
</head>
<body>
    <h2>Listado Actualizado de Nuestras Asignatura</h2>
    <h4><a class= "boton" href=" {% url 'migrate_01:crear_asignatura' %} ">Crear otra asignatura</a></h4>
    <table class="table">
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>departamento_id</th>
            <th>profesor_id</th>
            <th></th>
            <th></th>
        </tr>    

    {% for asignatura in asignatura %}
        <tr>
            <td>{{asignatura.id}}</td>
            <td>{{asignatura.nombre}}</td>
            <td>{{asignatura.descripcion}}</td>
            <td>{{asignatura.departamento_id_id}}</td>
            <td>{{asignatura.profesor_id_id}}</td>
            <td>
                <a class="boton" href="{% url 'migrate_01:editar_asignatura' id=asignatura.id %}"> Editar</a>
            </td>
            <td>
                <a class="boton" href="{% url 'migrate_01:eliminar_asignatura' id=asignatura.id %}"> Eliminar</a>
            </td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

mo6_ind6/Mo6 indi5/migrate_01/templates/migrate_01/ver_transportistas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in transportistas  %}
    <p>{{i}}</p>
    {% endfor %} 
</body>
</html>